==PREFS==
xml.formatter.line.preserve=1
xml.formatter.line.after.non.xml=1
xml.formatter.line.after.non.xml=1
xml.formatter.line.after.element=0
xml.formatter.wrap.comments.length=80
xml.formatter.wrap.comments=false
xml.formatter.formatter.indentation.size=4
xml.formatter.formatter.tabulation.size=4
xml.formatter.formatter.tabulation.char=space
==CONTENT==
<?xml version="1.0"?>
<!DOCTYPE note [
  <!ELEMENT note    (to+,from?,heading,img,body*)>
  <!ELEMENT to      (#PCDATA)>
  <!ELEMENT from    (#PCDATA)>
  <!ELEMENT img     (EMPTY)>
  <!ELEMENT heading (#PCDATA)>
  <!ELEMENT body    (ANY)>
]>
<note>
  <to>Tove</to>
  <from>Jani</from>
  <img src="me.jpg"/>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend</body>
</note>

==FORMATTED==
<?xml version="1.0"?>
<!DOCTYPE note [
<!ELEMENT note    (to+,from?,heading,img,body*)>
<!ELEMENT to      (#PCDATA)>
<!ELEMENT from    (#PCDATA)>
<!ELEMENT img     (EMPTY)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body    (ANY)>
]>
<note>
    <to>
        Tove
    </to>
    <from>
        Jani
    </from>
    <img src="me.jpg"/>
    <heading>
        Reminder
    </heading>
    <body>
        Don't forget me this weekend
    </body>
</note>

